apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jwtSecret: {{ .Values.backend.secrets.jwtSecret | quote }}
  salt: {{ .Values.backend.secrets.salt | quote }}
